version: "2.1"
services:
  jenkins:
    privileged: true
    image: jenkins:custom
    container_name: jenkins
    environment:
      JENKINS_OPTS: '"--httpPort=8080"'
    ports:
      - "8080:8080"
      - "50000:50000"
    network_mode: bridge
    volumes:
    # - /mnt/d/jenkins/data:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock

