version: '2'
services:
  zookeeper:
    image: registry.onesaitplatform.com/onesaitplatform/zookeeper-secured:stable
    container_name: zookeeper
    environment:
     - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - datanetwork
networks:
  datanetwork:
    external: true
